# Generated by Django 4.2.27 on 2026-01-01 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeddingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groom_name', models.CharField(default='Nguyễn Phước Hải', max_length=100)),
                ('bride_name', models.CharField(default='Dương Hà Giang', max_length=100)),
                ('groom_parents_dad', models.CharField(default='Ông Nguyễn Văn Học', max_length=100)),
                ('groom_parents_mom', models.CharField(default='Bà Phùng Thị Bạch Yến', max_length=100)),
                ('groom_address', models.CharField(default='131 Rạch Ông Kinh, P. Long Tuyền, TP. Cần Thơ', max_length=255)),
                ('bride_parents_dad', models.CharField(default='Ông Dương Huy Thu', max_length=100)),
                ('bride_parents_mom', models.CharField(default='Bà Nguyễn Thị Hoa', max_length=100)),
                ('bride_address', models.CharField(default='240 Lê Duẩn, Thôn 12, Xã Ea Knốp, H. Ea Kar, T. Đắk Lắk', max_length=255)),
                ('ceremony_date', models.DateTimeField(blank=True, null=True)),
                ('ceremony_time_str', models.CharField(default='08:00', max_length=50)),
                ('ceremony_date_str', models.CharField(default='Thứ Năm, 29/01/2026', max_length=100)),
                ('ceremony_location', models.CharField(default='Tại tư gia nhà trai', max_length=255)),
                ('ceremony_address', models.CharField(default='131 Rạch Ông Kinh, P. Long Tuyền, TP. Cần Thơ', max_length=255)),
                ('ceremony_lunar_date', models.CharField(default='(Tức ngày 11 tháng 12 năm Ất Tỵ)', max_length=100)),
                ('reception_date', models.DateTimeField(blank=True, null=True)),
                ('reception_time_str', models.CharField(default='10:30', max_length=50)),
                ('reception_date_str', models.CharField(default='CHỦ NHẬT | 31 | THÁNG 08', max_length=100)),
                ('reception_location', models.CharField(default='Queen Plaza Kỳ Hòa', max_length=255)),
                ('reception_address', models.CharField(default='Queen Plaza Kỳ Hòa, 16A Lê Hồng Phong, Phường 12, Quận 10, TP. Hồ Chí Minh', max_length=255)),
                ('reception_lunar_date', models.CharField(default='(Tức ngày 09/07 Ất Tỵ)', max_length=100)),
                ('google_map_link', models.URLField(blank=True, default='https://maps.app.goo.gl/somewhere', max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Wedding Info',
            },
        ),
    ]
