# Generated by Django 4.2.27 on 2026-01-01 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weddinginfo',
            name='bride_photo',
            field=models.ImageField(blank=True, help_text="Upload bride's photo (square ratio recommended)", null=True, upload_to='couple/'),
        ),
        migrations.AddField(
            model_name='weddinginfo',
            name='groom_photo',
            field=models.ImageField(blank=True, help_text="Upload groom's photo (square ratio recommended)", null=True, upload_to='couple/'),
        ),
        migrations.CreateModel(
            name='WeddingAlbumPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='album/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wedding_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_photos', to='invitation.weddinginfo')),
            ],
        ),
    ]
